---
title: "Assignment-2"
author: "Nikitha Chigurupati"
date: "10/5/2022"
output: html_document
---

```{r}
#Importing the required packages
library('caret')
library('ISLR')
library('dplyr')
library('class')
```

```{r}
#Importing the data into R Studio
UniversalBank <- read.csv("C:/Users/Nikitha/Downloads/UniversalBank.csv")
```

#QUESTION-1
```{r}
#Performing a K-NN classification with all attributes except ID and ZIP code.
UniversalBank$ID <- NULL
UniversalBank$ZIP.Code <- NULL
summary(UniversalBank)
UniversalBank$Personal.Loan =  as.factor(UniversalBank$Personal.Loan)
```

```{r}
#Using the preProcess() from the caret package to normalize the data by dividing into training and validation
Model_norm <- preProcess(UniversalBank[, -8],method = c("center", "scale"))
summary(UniversalBank)
UniversalBank_norm <- predict(Model_norm,UniversalBank)
summary(UniversalBank_norm)

Index_Train <- createDataPartition(UniversalBank$Personal.Loan, p = 0.6, list = FALSE)
Train = UniversalBank_norm[Index_Train,]
validation = UniversalBank_norm[-Index_Train,]
```

```{r}
#Prediction of data
library(FNN)
Predict = data.frame(Age = 40, Experience = 10, Income = 84, Family = 2,
                     CCAvg = 2, Education = 1, Mortgage = 0, Securities.Account =
                       0, CD.Account = 0, Online = 1, CreditCard = 1)
print(Predict)
Predict_Norm <- predict(Model_norm,Predict)
Prediction <- knn(train= as.data.frame(Train[,1:7,9:12]),
                  test = as.data.frame(Predict_Norm[,1:7,9:12]),
                  cl= Train$Personal.Loan,
                  k=1)
print(Prediction)
```

#QUESTION-2
```{r}
set.seed(123)
UniversalBank <- trainControl(method= "repeatedcv", number = 3, repeats = 2)
searchGrid = expand.grid(k=1:10)
knn.model = train(Personal.Loan~., data = Train, method = 'knn', tuneGrid = searchGrid,trControl = UniversalBank)
knn.model
#The value of k is 3, which strikes a compromise between underfitTing and overfitting of the data.
#Accuracy was used to select the optimal model using the largest value for the model was k = 3.
```

#QUESTION-3
```{r}
prediction_of_bank <- predict(knn.model,validation)
confusionMatrix(prediction_of_bank,validation$Personal.Loan)
#This matrix has a 95.9% accuracy.
```

#QUESTION-4
```{r}
For_Predict_Norm = data.frame(Age = 40, Experience = 10, Income = 84, Family = 2,
                              CCAvg = 2, Education = 1, Mortgage = 0,
                              Securities.Account =0, CD.Account = 0, Online = 1,
                              CreditCard = 1)
For_Predict_Norm = predict(Model_norm, For_Predict_Norm)
predict(knn.model, For_Predict_Norm)
```

#QUESTION-5
```{r}
#Creating Training, Test, and validation sets from the data collection.
Train_size = 0.5 #training(50%)
Index_Train = createDataPartition(UniversalBank_norm$Personal.Loan, p = 0.5, list = FALSE)
Train = UniversalBank_norm[Index_Train,]

valid_size = 0.3 #validation(30%)
Index_Validation = createDataPartition(UniversalBank_norm$Personal.Loan, p = 0.3, list = FALSE)
validation = UniversalBank_norm[Index_Validation,]

Test_size = 0.2 #Test Data(20%)
Index_Test = createDataPartition(UniversalBank_norm$Personal.Loan, p = 0.2, list = FALSE)
Test = UniversalBank_norm[Index_Test,]


Trainingknn <- knn(train = Train[,-8], test = Train[,-8], cl = Train[,8], k =3)
Validknn <- knn(train = Train[,-8], test = validation[,-8], cl = Train[,8], k =3)
Testingknn <- knn(train = Train[,-8], test = Test[,-8], cl = Train[,8], k =3)

Train_Predictors<-Train[,9:12] 
Test_Predictors<-Test[,9:12]

Train_labels <-Train[,8]
Test_labels  <-Test[,8]

Predicted_Test_labels <-knn(Train_Predictors, 
                            Test_Predictors, 
                            cl=Train_labels, 
                            k=3 )

library("gmodels")
CrossTable(x=Test_labels,y=Predicted_Test_labels, prop.chisq = FALSE) 

confusionMatrix(Trainingknn, Train[,8])
confusionMatrix(Validknn, validation[,8])
confusionMatrix(Testingknn, Test[,8])
```

