---
title: "Assignment 4"
author: "Nikitha Chigurupati"
date: "11/1/2022"
output:
  word_document: default
  html_document: default
---
```{r}
#Importing the Dataset
Pharma <- read.csv("C:/Users/Nikitha/Downloads/Pharmaceuticals.csv")
summary(Pharma)
str(Pharma)
```

```{r}
#Loading the Packages
library(readr)
library(dplyr)
library(caret)
library(factoextra)
library(tidyverse)
library(cluster)
library(gridExtra)
```

```{r}
#a. Use only the numerical variables (1 to 9) to cluster the 21 firms. Justify the various choices made in conducting the cluster analysis, such as weights for different variables, the specific clustering algorithm(s) used, the number of clusters formed, and so on. 

#Removing the Null Values in the dataset and selecting the Numercial variables.
colSums(is.na(Pharma))
row.names(Pharma)<- Pharma[,1]
Pharma_data_num<- Pharma[, 3:11]
head(Pharma_data_num)
```

```{r}
# Scaling and Normalisation the dataset.
Pharma_scale <- scale(Pharma_data_num)
head(Pharma_scale)
normal_data <- as.data.frame(scale(Pharma_data_num))
```

```{r}
# Computing K-means clustering  for different centers and Using multiple values of K and examine the differences in results
kmeans_1 <- kmeans(Pharma_scale, centers = 2, nstart = 30)
kmeans_2<- kmeans(Pharma_scale, centers = 5, nstart = 30)
kmeans_3<- kmeans(Pharma_scale, centers = 6, nstart = 30)
Plot_1<-fviz_cluster(kmeans_1, data = Pharma_scale)+ggtitle("k=2")
plot_2<-fviz_cluster(kmeans_2, data = Pharma_scale)+ggtitle("k=5")
plot_3<-fviz_cluster(kmeans_3, data = Pharma_scale)+ggtitle("k=6")
grid.arrange(Plot_1,plot_2,plot_3, nrow = 3)
```

```{r}
distance<- dist(Pharma_scale, method = "euclidean")
fviz_dist(distance)
```

```{r}
# Estimating the  number of clusters
# Elbow Method is used in scaling the data to determine the value of k
fviz_nbclust(normal_data, FUNcluster = kmeans, method = "wss") + labs(subtitle = "Elbow Method")

```

```{r}
# Silhouette Method is used in scaling the data to determine the number of clusters
fviz_nbclust(normal_data,FUNcluster = kmeans,method = "silhouette")+labs(subtitle="Silhouette Method")
```

```{r}
# Final analysis and Extracting results using 5 clusters and Visualize the results
set.seed(300)
final_Cluster<- kmeans(Pharma_scale, 5, nstart = 25)
print(final_Cluster)
clusplot(Pharma_scale,final_Cluster$cluster, color = TRUE, labels = 2,lines = 0)
```

```{r}
#b) Interpret the clusters with respect to the numerical variables used in forming the clusters.

#Cluster 1 - AHM,SGP,WYE,BMY,AZN, ABT, NVS, LLY ( lowest Market_Cap,lowest Beta,lowest PE_Ratio,highest Leverage,highest Rev_Growth.)

#Cluster 2 - BAY, CHTT, IVX (lowest Rev_Growth,highest Beta and levearge,lowest Net_Profit_Margin)

#Cluster 3 - WPI, MRX,ELN,AVE (lowest PE_Ratio,highest ROE,lowest ROA,lowest Net_Profit_Margin, highest Rev_Growth)

#Cluster 4 - AGN, PHA (lowest Beta,lowest Asset_Turnover, Highest PE Ratio)

#Cluster 5 - JNJ, MRK, PFE,GSK (Highest Market_Cap,ROE, ROA,Asset_Turnover Ratio and lowest Beta/PE Ratio)

Pharma_Cluster <- Pharma[,c(12,13,14)]%>% mutate(clusters = final_Cluster$cluster)%>% arrange(clusters, ascending = TRUE)
Pharma_Cluster

```


```{r}
#(c)Is there a pattern in the clusters with respect to the numerical variables (10 to 12)? 

plot1<-ggplot(Pharma_Cluster, mapping = aes(factor(clusters), fill=Median_Recommendation))+geom_bar(position = 'dodge')+labs(x ='No of clusters')
plot2<- ggplot(Pharma_Cluster, mapping = aes(factor(clusters),fill = Location))+geom_bar(position = 'dodge')+labs(x ='No of clusters')
plot3<- ggplot(Pharma_Cluster, mapping = aes(factor(clusters),fill = Exchange))+geom_bar(position = 'dodge')+labs(x ='No of clusters')
grid.arrange(plot1, plot2, plot3)  


#As per graph:- 

#Cluster 1 :The Hold median is the highest in this cluster , which also contains separate Hold, Moderate Buy, Moderate Sell, and Strong Buy medians. They are listed on the NYSE and come from the US, UK, and Switzerland.

#Cluster 2: Although the firms are evenly divided throughout AMEX, NASDAQ, and NYSE,  has a distinct Hold and Moderate Buy median, as well as a different count between the US and Germany.

#Cluster 3: listed on the NYSE, has separate counts for France, Ireland, and the US, and has equal moderate buy and sell medians.

#Cluster 4: dispersed throughout the US and UK, as well as being listed in, has the identical hold and moderate buy medians

#Cluster 5: #solely listed on the NYSE, equally dispersed in the US and Canada, with Hold and Moderate Buy medians.

#With respect to media Recommendation Variable ,the clusters follow a particular pattern:
#Cluster 1 and Cluster 2 has Hold Recommendation.
#Cluster 3, Cluster 4and Cluster 5 has moderate buy Recommendation.
```

```{r}
# (d)Provide an appropriate name for each cluster using any or all of the variables in the dataset.

#Cluster 1 :-  HIGH HOLD CLUSTER
#Cluster 2 :- HOLD CLUSTER
#Cluster 3 :- BUY-SELL CLUSTER
#Cluster 4 :- HOLD-BUY CLUSTER
#Cluster 5 :- HOLD-BUY CLUSTER